// Package: com.lightningkite.ktordb.live
// Generated by Khrysalis - this file will be overwritten.
import { ObserveModelApi } from '../ObserveModelApi'
import { HasId } from '../db/HasId'
import { ListChange } from '../db/ListChange'
import { Query } from '../db/Query'
import { xListComparatorGet } from '../db/SortPart'
import { WebSocketIsh, multiplexedSocketReified } from './sockets'
import { Comparable, Comparator, EqualOverrideMap, compareBy, join, listRemoveAll, runOrNull, safeEq, xMutableMapGetOrPut } from '@lightningkite/khrysalis-runtime'
import { execPipe, map } from 'iter-tools-es'
import { NEVER, Observable } from 'rxjs'
import { catchError, map as oMap, publishReplay, refCount, switchMap, tap } from 'rxjs/operators'

//! Declares com.lightningkite.ktordb.live.LiveObserveModelApi
export class LiveObserveModelApi<Model extends HasId<string>> extends ObserveModelApi<Model> {
    public constructor(public readonly openSocket: ((query: Query<Model>) => Observable<Array<Model>>)) {
        super();
        this.alreadyOpen = new EqualOverrideMap<Query<Model>, Observable<Array<Model>>>();
    }
    
    
    
    
    public readonly alreadyOpen: Map<Query<Model>, Observable<Array<Model>>>;
    
    public observe(query: Query<Model>): Observable<Array<Model>> {
        //multiplexedSocket<ListChange<Model>, Query<Model>>("$multiplexUrl?jwt=$token", path)
        return xMutableMapGetOrPut<Query<Model>, Observable<Array<Model>>>(this.alreadyOpen, query, (): Observable<Array<Model>> => (this.openSocket(query)
                .pipe(tap({ unsubscribe: (): void => {
                this.alreadyOpen.delete(query);
            } }))
                .pipe(publishReplay(1))
            .pipe(refCount())));
    }
}
export namespace LiveObserveModelApi {
    //! Declares com.lightningkite.ktordb.live.LiveObserveModelApi.Companion
    export class Companion {
        private constructor() {
        }
        public static INSTANCE = new Companion();
        
        public create<Model extends HasId<string>>(Model: Array<any>, multiplexUrl: string, token: string, headers: Map<string, string>, path: string): LiveObserveModelApi<Model> {
            return new LiveObserveModelApi<Model>((query: Query<Model>): Observable<Array<Model>> => (xObservableToListObservable<Model>(multiplexedSocketReified<ListChange<Model>, Query<Model>>([ListChange, Model], [Query, Model], `${multiplexUrl}?jwt=${token}&${execPipe(new Set([...headers.entries()]), map((it: [string, string]): string => (`${it[0]}=${it[1]}`)), join("&"))}`, path, undefined)
                    .pipe(switchMap((it: WebSocketIsh<ListChange<Model>, Query<Model>>): Observable<ListChange<Model>> => {
                    it.send(query);
                    return it.messages.pipe(catchError((it: any): Observable<ListChange<Model>> => (NEVER)));
            })), xListComparatorGet(query.orderBy) ?? compareBy<Model>((it: Model): (Comparable<(any | null)> | null) => (it._id)))));
        }
    }
}

//! Declares com.lightningkite.ktordb.live.toListObservable>io.reactivex.rxjava3.core.Observablecom.lightningkite.ktordb.ListChangecom.lightningkite.ktordb.live.toListObservable.T
export function xObservableToListObservable<T extends HasId<string>>(this_: Observable<ListChange<T>>, ordering: Comparator<T>): Observable<Array<T>> {
    const localList = ([] as Array<T>);
    return this_.pipe(oMap((it: ListChange<T>): Array<T> => {
        const it_14 = it.wholeList;
        if (it_14 !== null) {
            localList.length = 0; localList.push(...it_14.slice().sort(ordering));
        }
        const it_16 = it._new;
        if (it_16 !== null) {
            listRemoveAll(localList, (o: T): boolean => (safeEq(it_16._id, o._id)));
            let index = localList.findIndex((inList: T): boolean => (ordering(it_16, inList) < 0));
            if (index === (-1)) { index = localList.length }
            localList.splice(index, 0, it_16);
        } else {
            const it_23 = it.old;
            if (it_23 !== null) {
                listRemoveAll(localList, (o: T): boolean => (safeEq(it_23._id, o._id)));
            }
        }
        return localList;
    }));
}